server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 单机
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #集群
      defaultZone: http://eureka7001.com:7001/eureka/   #单机
  #      defaultZone: http://eureka7002.com:7002/eureka/  #集群
  server:
    enable-self-preservation: false # 默认开启自我保护 现在设置关闭
    eviction-interval-timer-in-ms: 2000
#  server:
#    # 关闭自我保护机制，保证不可用服务被及时剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000


